net.Receive('SendAdvert',function( len )
    local msg = net.ReadString()
    local ply = net.ReadEntity()
    chat.AddText(team.GetColor(ply:Team()), "[Advert] "..ply:GetName()..": ", CUSTOMADVERT.Config.advertTextColor, msg)
end)
net.Receive('SendPoliceAdvert',function( len )
    local msg = net.ReadString()
    chat.AddText(Color(0,132,180), "[Advert] Police: ", CUSTOMADVERT.Config.advertTextColor, msg)
end)
net.Receive('SendAnonymousAdvert',function( len )
    local msg = net.ReadString()
    chat.AddText(Color(178,34,34), "[Advert] **Anonymous User**: ", CUSTOMADVERT.Config.advertTextColor, msg)
end)
net.Receive('SendTweet',function( len )
    local msg = net.ReadString()
    local ply = net.ReadEntity()
    chat.AddText(Color(0,127,237), "[Tweet] "..ply:GetName()..": ", Color(255,255,255), msg)
end)
net.Receive('SendErrorNotification',function(len)
    local msg = net.ReadString()
    notification.AddLegacy( msg, NOTIFY_ERROR, 2 )
end)
